export const SERVICES = [
  {
    id: 'agentic-ai',
    icon: 'AI',
    title: 'Agentic AI Engineering',
    description:
      'Design and deploy governed multi-agent systems, LLM orchestration pipelines, RAG architectures, AI copilots, and enterprise automation workflows.',
    tags: ['ADAS', 'LangGraph', 'MCP', 'RAG', 'LLM', 'AutoGen'],
    color: '#3157D5',
    highlight: true,
    capabilities: [
      'Multi-agent orchestration (ADAS)',
      'RAG + vector database pipelines',
      'LLM fine-tuning & prompt engineering',
      'Enterprise AI copilots',
      'MCP server integration',
      'Agentic workflow automation',
    ],
  },
  {
    id: 'generative-ai',
    icon: 'GL',
    title: 'Generative AI & LLM Systems Design',
    description:
      'Production LLM architecture covering foundation model selection, prompt engineering, domain fine-tuning, evaluation frameworks, GenAI safety guardrails, and deployment observability.',
    tags: ['GPT-4o', 'Claude', 'Gemini', 'Llama', 'LangChain', 'RAGAS'],
    color: '#7C3AED',
    highlight: true,
    capabilities: [
      'Foundation model selection & benchmarking',
      'Prompt architecture & few-shot design',
      'Domain fine-tuning on enterprise data',
      'LLM evaluation (RAGAS, LLM-as-judge)',
      'GenAI guardrails & output validation',
      'LLM observability & token optimisation',
    ],
  },
  {
    id: 'data-engineering',
    icon: 'DE',
    title: 'Data Engineering & Platforms',
    description:
      'Medallion lakehouse architectures, high-throughput ETL/ELT pipelines, real-time Spark/Kafka processing, Databricks, Synapse, and enterprise warehouse modernisation.',
    tags: ['Databricks', 'Synapse', 'Delta Lake', 'Kafka', 'Airflow'],
    color: '#0E9488',
    highlight: true,
    capabilities: [
      'Bronze-Silver-Gold medallion architecture',
      'Azure Synapse + Databricks pipelines',
      'SAP ECC / Datasphere integrations',
      'Real-time streaming with Kafka',
      'Apache Airflow orchestration',
      'Data quality & observability',
    ],
  },
  {
    id: 'data-science',
    icon: 'DS',
    title: 'Data Science & Advanced Analytics',
    description:
      'Predictive modelling, statistical analysis, demand forecasting, customer intelligence, prescriptive optimisation, and executive-grade decision intelligence.',
    tags: ['Predictive', 'Forecasting', 'Statistical ML', 'Power BI', 'Python'],
    color: '#B7791F',
    highlight: true,
    capabilities: [
      'Predictive & prescriptive modelling',
      'Time-series forecasting',
      'Customer segmentation & CLV',
      'Statistical hypothesis testing',
      'Advanced Power BI / Tableau dashboards',
      'Applied Mathematics for decision intelligence',
    ],
  },
  {
    id: 'cloud-architecture',
    icon: 'CL',
    title: 'Cloud Architecture',
    description:
      'Multi-cloud architecture across Azure, AWS and GCP with Infrastructure-as-Code, Kubernetes orchestration, DevOps/GitOps pipelines, security controls, and cost governance.',
    tags: ['Azure', 'AWS', 'GCP', 'Kubernetes', 'Terraform'],
    color: '#2447B8',
    highlight: false,
    capabilities: [
      'Azure, AWS and GCP certified architecture',
      'Enterprise landing zones and governance',
      'Kubernetes & container orchestration',
      'Terraform / Bicep IaC',
      'DevOps + GitOps pipelines',
      'FinOps & cloud cost optimisation',
    ],
  },
  {
    id: 'mlops',
    icon: 'MO',
    title: 'MLOps & DataOps',
    description:
      'End-to-end ML lifecycle management with experiment tracking, model registry, CI/CD for ML, drift monitoring, feature stores, and DataOps governance frameworks.',
    tags: ['MLflow', 'AzureML', 'SageMaker', 'CI/CD', 'Feature Store'],
    color: '#C2415D',
    highlight: false,
    capabilities: [
      'ML pipeline automation',
      'Model monitoring & drift detection',
      'Feature store design',
      'A/B testing infrastructure',
      'DataOps governance frameworks',
      'Automated retraining pipelines',
    ],
  },
  {
    id: 'managed-services',
    icon: 'MS',
    title: 'Managed Services',
    description:
      'Deployment is day one. We stay on to run, monitor, and optimise what we build — so your AI and data platforms keep delivering value long after go-live. Available as a monthly retainer alongside or independent of project delivery.',
    note: 'Engage us project-by-project, or keep us on retainer to operate what we\'ve built. Senior-led, same team from architecture through operations.',
    tags: ['Azure Monitor', 'FinOps', 'SLA', 'SOC 2', 'Retainer'],
    color: '#334155',
    highlight: false,
    capabilities: [
      'Azure environment monitoring: 24/7 infrastructure health, uptime/SLA tracking via Azure Monitor and Log Analytics, proactive alerting and incident response playbooks',
      'AI workload management: ongoing operation of agentic systems and LLM pipelines, including performance tracking, retraining triggers, prompt/version control and agent orchestration health checks',
      'Data platform operations: day-to-day running of lakehouse and warehouse environments across Databricks, Synapse and Fabric, with pipeline monitoring, job scheduling, data quality checks and schema drift detection',
      'Security & compliance support: access control audits, vulnerability monitoring and compliance reporting (SOC 2, GDPR, NDPR) for AI and data systems in production',
      'Cost optimisation: continuous right-sizing of cloud resources, reserved instance/savings-plan management and workload-level cost attribution',
      'Ongoing application support: L2/L3 support for deployed applications, including fixes, minor enhancements, uptime monitoring and ticket-based SLAs',
      'Cloud FinOps: full FinOps practice covering budget governance, chargeback/showback models, unit economics tracking and executive cost dashboards',
    ],
  },
  {
    id: 'azure-monitoring',
    icon: 'AM',
    title: 'Azure Environment Monitoring',
    description:
      '24/7 infrastructure health monitoring, uptime/SLA tracking via Azure Monitor and Log Analytics, proactive alerting, and incident response playbooks.',
    tags: ['Azure Monitor', 'Log Analytics', 'SLA', 'Alerting'],
    color: '#2563EB',
    highlight: false,
    capabilities: [
      '24/7 infrastructure health monitoring',
      'Uptime and SLA tracking via Azure Monitor and Log Analytics',
      'Proactive alerting on anomalies and threshold breaches',
      'Incident response playbooks and escalation paths',
    ],
  },
  {
    id: 'ai-workload-management',
    icon: 'WM',
    title: 'AI Workload Management',
    description:
      'Ongoing operation of deployed agentic systems and LLM pipelines: performance tracking, retraining triggers, prompt/version control, and agent orchestration health checks.',
    tags: ['Agentic AI', 'LLMOps', 'Prompt Versioning', 'Monitoring'],
    color: '#4F46E5',
    highlight: false,
    capabilities: [
      'Performance tracking for agentic systems and LLM pipelines',
      'Retraining triggers based on drift and quality signals',
      'Prompt and model version control',
      'Agent orchestration health checks',
    ],
  },
  {
    id: 'data-platform-ops',
    icon: 'DO',
    title: 'Data Platform Operations',
    description:
      'Day-to-day running of lakehouse and warehouse environments across Databricks, Synapse, and Fabric — pipeline monitoring, job scheduling, data quality checks, schema drift detection.',
    tags: ['Databricks', 'Synapse', 'Fabric', 'DataOps'],
    color: '#0F766E',
    highlight: false,
    capabilities: [
      'Day-to-day operation of Databricks, Synapse and Fabric environments',
      'Pipeline monitoring and job scheduling',
      'Data quality checks and validation',
      'Schema drift detection',
    ],
  },
  {
    id: 'security-compliance-support',
    icon: 'SC',
    title: 'Security & Compliance Support',
    description:
      'Access control audits, vulnerability monitoring, and compliance reporting (SOC 2, GDPR, NDPR) for AI and data systems in production.',
    tags: ['SOC 2', 'GDPR', 'NDPR', 'Access Control'],
    color: '#B91C1C',
    highlight: false,
    capabilities: [
      'Access control audits',
      'Continuous vulnerability monitoring',
      'Compliance reporting for SOC 2, GDPR and NDPR',
      'Security reviews for production AI and data systems',
    ],
  },
  {
    id: 'cost-optimisation',
    icon: 'CO',
    title: 'Cost Optimisation',
    description:
      'Continuous right-sizing of cloud resources, reserved instance/savings-plan management, and workload-level cost attribution.',
    tags: ['FinOps', 'Cost Management', 'Cloud Spend'],
    color: '#65A30D',
    highlight: false,
    capabilities: [
      'Continuous right-sizing of cloud resources',
      'Reserved instance and savings-plan management',
      'Workload-level cost attribution',
      'Ongoing spend reviews and recommendations',
    ],
  },
  {
    id: 'application-support',
    icon: 'AS',
    title: 'Ongoing Application Support',
    description:
      'L2/L3 support for deployed applications — fixes, minor enhancements, uptime monitoring, ticket-based SLAs.',
    tags: ['Support', 'SLA', 'L2/L3', 'Maintenance'],
    color: '#0891B2',
    highlight: false,
    capabilities: [
      'L2/L3 support for deployed applications',
      'Bug fixes and minor enhancements',
      'Uptime monitoring',
      'Ticket-based SLAs',
    ],
  },
  {
    id: 'cloud-finops',
    icon: 'CF',
    title: 'Cloud FinOps',
    description:
      'Full FinOps practice: budget governance, chargeback/showback models, unit economics tracking, and executive cost dashboards.',
    tags: ['FinOps', 'Budgeting', 'Chargeback', 'Dashboards'],
    color: '#7C2D12',
    highlight: false,
    capabilities: [
      'Budget governance',
      'Chargeback and showback models',
      'Unit economics tracking',
      'Executive cost dashboards',
    ],
  },
  {
    id: 'ai-advisory',
    icon: 'AV',
    title: 'AI Advisory & Governance',
    description:
      'AI readiness assessment, transformation roadmaps, responsible AI policy, model risk management, regulatory compliance, and board-level AI governance for enterprise programmes.',
    tags: ['AI Strategy', 'Responsible AI', 'EU AI Act', 'NIST RMF', 'Model Risk', 'Governance'],
    color: '#047857',
    highlight: false,
    capabilities: [
      'AI readiness & opportunity mapping',
      'Enterprise AI strategy & roadmap',
      'Responsible AI frameworks & ethics policy',
      'Model risk management & audit-readiness',
      'EU AI Act & NIST RMF compliance',
      'Executive AI & board-level governance',
    ],
  },
  {
    id: 'software-engineering',
    icon: 'SE',
    title: 'Enterprise Software Engineering',
    description:
      'Production-grade backend systems, REST and GraphQL APIs, microservices, and SaaS platforms in C# .NET, Python FastAPI, and Node.js, built for enterprise scale.',
    tags: ['C# .NET', 'FastAPI', 'MERN', 'Microservices', 'GraphQL'],
    color: '#10275F',
    highlight: false,
    capabilities: [
      'C# ASP.NET Core 10 systems',
      'Python FastAPI services',
      'MERN stack SaaS platforms',
      'Microservices architecture',
      'RESTful & GraphQL APIs',
      'Event-driven systems (Azure Service Bus)',
    ],
  },
  {
    id: 'fintech-blockchain',
    icon: 'FX',
    title: 'FinTech & Blockchain',
    description:
      'Digital finance platforms, payment integrations, blockchain services, Web3 APIs, and regulatory-aware financial technology solutions for secure transaction flows.',
    tags: ['Solidity', 'Ethereum', 'Web3', 'DeFi', 'Payments'],
    color: '#6F5B22',
    highlight: false,
    capabilities: [
      'Ethereum smart contract development',
      'DeFi protocol integrations',
      'Digital payment gateway systems',
      'Web3.js / Ethers.js APIs',
      'Regulatory compliance (NUPRC/DPR)',
      'Financial data analytics',
    ],
  },
  {
    id: 'digital-marketing',
    icon: 'DM',
    title: 'Digital Marketing',
    description:
      'AI-augmented digital marketing across the channels that matter, from LinkedIn B2B outreach and YouTube content strategy to email automation and paid social campaigns.',
    tags: ['LinkedIn', 'YouTube', 'Facebook', 'Instagram', 'Email'],
    color: '#0EA5E9',
    highlight: false,
    capabilities: [
      'LinkedIn thought leadership & B2B outreach',
      'YouTube channel strategy & content production',
      'Facebook & Instagram paid campaign management',
      'Email marketing automation & nurture sequences',
    ],
  },
  {
    id: 'cybersecurity',
    icon: 'CS',
    title: 'Cybersecurity',
    description:
      'Protect your cloud infrastructure and enterprise systems with security architecture, compliance auditing, IAM design, and continuous threat monitoring across AWS, Azure, and GCP.',
    tags: ['AWS', 'Azure', 'GCP', 'Zero Trust', 'SIEM'],
    color: '#F43F5E',
    highlight: false,
    capabilities: [
      'Cloud security posture management (CSPM)',
      'Identity & access management (IAM / Zero Trust)',
      'Threat detection, SIEM & incident response',
      'Compliance auditing (ISO 27001, SOC 2, NDPA)',
    ],
  },
  {
    id: 'statistical-analysis',
    icon: 'SA',
    title: 'Statistical Analysis',
    description:
      'Rigorous statistical methods applied to complex enterprise datasets, from exploratory analysis and hypothesis testing to Bayesian inference and high-dimensional data modelling.',
    tags: ['Python', 'R', 'Bayesian', 'Hypothesis Testing', 'SciPy'],
    color: '#06B6D4',
    highlight: false,
    capabilities: [
      'Descriptive & inferential statistics',
      'Regression, classification & hypothesis testing',
      'Bayesian inference & probabilistic modelling',
      'Multivariate & high-dimensional data analysis',
    ],
  },
  {
    id: 'industrial-mathematics',
    icon: 'IM',
    title: 'Industrial Mathematics',
    description:
      'Translate complex engineering and operational problems into mathematical models, driving process optimisation, simulation, and evidence-based decisions across energy, manufacturing, and logistics.',
    tags: ['Optimisation', 'Simulation', 'ODE / PDE', 'Numerical Methods', 'SciPy'],
    color: '#84CC16',
    highlight: false,
    capabilities: [
      'Mathematical modelling & simulation',
      'Operations research & convex optimisation',
      'Differential equations for physical systems',
      'Numerical methods & computational analysis',
    ],
  },
  {
    id: 'financial-mathematics',
    icon: 'FM',
    title: 'Financial Mathematics',
    description:
      'Quantitative finance solutions for pricing, risk, and portfolio problems, bridging stochastic calculus and functional analysis with production-grade financial systems.',
    tags: ['Stochastic Calculus', 'Monte Carlo', 'VaR / CVaR', 'Quant Finance', 'QuantLib'],
    color: '#F97316',
    highlight: false,
    capabilities: [
      'Derivatives pricing & stochastic modelling',
      'Risk modelling: VaR, CVaR & stress testing',
      'Portfolio optimisation & asset allocation',
      'Algorithmic & quantitative strategy development',
    ],
  },
  {
    id: 'explainable-ai',
    icon: 'XA',
    title: 'Explainable AI (XAI)',
    description:
      'Mathematical interpretability frameworks for AI models deployed in regulated industries, making black-box predictions auditable, defensible, and compliant with emerging AI regulation.',
    tags: ['SHAP', 'LIME', 'Fairness', 'EU AI Act', 'Model Audit'],
    color: '#A78BFA',
    highlight: false,
    capabilities: [
      'SHAP, LIME & feature attribution analysis',
      'Model transparency & audit trail design',
      'Bias detection & fairness testing',
      'XAI for finance, healthcare & legal systems',
    ],
  },
  {
    id: 'nlp-document-intelligence',
    icon: 'NL',
    title: 'NLP & Document Intelligence',
    description:
      'Transform unstructured text into enterprise knowledge through contract analysis, multilingual NLP, document classification, and semantic search systems tailored for African and global markets.',
    tags: ['Transformers', 'spaCy', 'Semantic Search', 'HuggingFace', 'NER'],
    color: '#34D399',
    highlight: false,
    capabilities: [
      'Contract & document intelligence pipelines',
      'Multilingual NLP for African language contexts',
      'Semantic search & knowledge graph construction',
      'Named entity recognition & text classification',
    ],
  },
  {
    id: 'technical-training',
    icon: 'TT',
    title: 'Technical Training & Capacity Building',
    description:
      'Enterprise upskilling programmes in AI, data engineering, cloud, and advanced mathematics, delivered by practitioners with real production experience and graduate-level mathematical depth.',
    tags: ['Bootcamp', 'Corporate Training', 'AI Upskilling', 'Workshops', 'Certification'],
    color: '#FBBF24',
    highlight: false,
    capabilities: [
      'Agentic AI & LLM engineering bootcamps',
      'Data engineering & cloud architecture programmes',
      'Applied mathematics for AI & ML teams',
      'Bespoke corporate training & workshops',
    ],
  },
  {
    id: 'quantitative-research',
    icon: 'QR',
    title: 'Quantitative Research & Consulting',
    description:
      'Mathematical consulting for organisations that need rigorous quantitative foundations, including actuarial modelling, applied functional analysis, and bespoke research for complex scientific and business problems.',
    tags: ['Functional Analysis', 'Actuarial', 'Research', 'Applied Math', 'Consulting'],
    color: '#E879F9',
    highlight: false,
    capabilities: [
      'Functional analysis & operator theory applications',
      'Actuarial & insurance modelling',
      'Bespoke mathematical research & white papers',
      'Academic-industry research partnerships',
    ],
  },
  {
    id: 'iot-edge-ai',
    icon: 'IE',
    title: 'IoT & Edge AI',
    description:
      'Deploy lightweight AI models directly on edge devices and IoT infrastructure, enabling real-time industrial monitoring, predictive maintenance, and low-latency intelligence at the network edge.',
    tags: ['Edge AI', 'TensorFlow Lite', 'ONNX', 'IoT', 'MQTT'],
    color: '#38BDF8',
    highlight: false,
    capabilities: [
      'Edge model compression & quantisation',
      'IoT sensor data pipelines & telemetry',
      'Predictive maintenance & anomaly detection',
      'Industrial AI for energy & manufacturing sectors',
    ],
  },
]

export default SERVICES
