export const SERVICES = [
  {
    id: 'agentic-ai',
    icon: 'AI',
    title: 'Agentic AI Engineering',
    description:
      'Design and deploy governed multi-agent systems, LLM orchestration pipelines, RAG architectures, AI copilots, and enterprise automation workflows.',
    tags: ['ADAS', 'LangGraph', 'MCP', 'RAG', 'LLM', 'AutoGen'],
    color: '#3157D5',
    highlight: true,
    capabilities: [
      'Multi-agent orchestration (ADAS)',
      'RAG + vector database pipelines',
      'LLM fine-tuning & prompt engineering',
      'Enterprise AI copilots',
      'MCP server integration',
      'Agentic workflow automation',
    ],
  },
  {
    id: 'generative-ai',
    icon: 'GL',
    title: 'Generative AI & LLM Systems Design',
    description:
      'Production LLM architecture covering foundation model selection, prompt engineering, domain fine-tuning, evaluation frameworks, GenAI safety guardrails, and deployment observability.',
    tags: ['GPT-4o', 'Claude', 'Gemini', 'Llama', 'LangChain', 'RAGAS'],
    color: '#7C3AED',
    highlight: true,
    capabilities: [
      'Foundation model selection & benchmarking',
      'Prompt architecture & few-shot design',
      'Domain fine-tuning on enterprise data',
      'LLM evaluation (RAGAS, LLM-as-judge)',
      'GenAI guardrails & output validation',
      'LLM observability & token optimisation',
    ],
  },
  {
    id: 'data-engineering',
    icon: 'DE',
    title: 'Data Engineering & Platforms',
    description:
      'Medallion lakehouse architectures, high-throughput ETL/ELT pipelines, real-time Spark/Kafka processing, Databricks, Synapse, and enterprise warehouse modernisation.',
    tags: ['Databricks', 'Synapse', 'Delta Lake', 'Kafka', 'Airflow'],
    color: '#0E9488',
    highlight: false,
    capabilities: [
      'Bronze-Silver-Gold medallion architecture',
      'Azure Synapse + Databricks pipelines',
      'SAP ECC / Datasphere integrations',
      'Real-time streaming with Kafka',
      'Apache Airflow orchestration',
      'Data quality & observability',
    ],
  },
  {
    id: 'data-science',
    icon: 'DS',
    title: 'Data Science & Advanced Analytics',
    description:
      'Predictive modelling, statistical analysis, demand forecasting, customer intelligence, prescriptive optimisation, and executive-grade decision intelligence.',
    tags: ['Predictive', 'Forecasting', 'Statistical ML', 'Power BI', 'Python'],
    color: '#B7791F',
    highlight: true,
    capabilities: [
      'Predictive & prescriptive modelling',
      'Time-series forecasting',
      'Customer segmentation & CLV',
      'Statistical hypothesis testing',
      'Advanced Power BI / Tableau dashboards',
      'Applied Mathematics for decision intelligence',
    ],
  },
  {
    id: 'cloud-architecture',
    icon: 'CL',
    title: 'Cloud Architecture',
    description:
      'Multi-cloud architecture across Azure, AWS and GCP with Infrastructure-as-Code, Kubernetes orchestration, DevOps/GitOps pipelines, security controls, and cost governance.',
    tags: ['Azure', 'AWS', 'GCP', 'Kubernetes', 'Terraform'],
    color: '#2447B8',
    highlight: false,
    capabilities: [
      'Azure, AWS and GCP certified architecture',
      'Enterprise landing zones and governance',
      'Kubernetes & container orchestration',
      'Terraform / Bicep IaC',
      'DevOps + GitOps pipelines',
      'FinOps & cloud cost optimisation',
    ],
  },
  {
    id: 'mlops',
    icon: 'MO',
    title: 'MLOps & DataOps',
    description:
      'End-to-end ML lifecycle management with experiment tracking, model registry, CI/CD for ML, drift monitoring, feature stores, and DataOps governance frameworks.',
    tags: ['MLflow', 'AzureML', 'SageMaker', 'CI/CD', 'Feature Store'],
    color: '#C2415D',
    highlight: false,
    capabilities: [
      'ML pipeline automation',
      'Model monitoring & drift detection',
      'Feature store design',
      'A/B testing infrastructure',
      'DataOps governance frameworks',
      'Automated retraining pipelines',
    ],
  },
  {
    id: 'ai-advisory',
    icon: 'AV',
    title: 'AI Advisory & Governance',
    description:
      'AI readiness assessment, transformation roadmaps, responsible AI policy, model risk management, regulatory compliance, and board-level AI governance for enterprise programmes.',
    tags: ['AI Strategy', 'Responsible AI', 'EU AI Act', 'NIST RMF', 'Model Risk', 'Governance'],
    color: '#047857',
    highlight: false,
    capabilities: [
      'AI readiness & opportunity mapping',
      'Enterprise AI strategy & roadmap',
      'Responsible AI frameworks & ethics policy',
      'Model risk management & audit-readiness',
      'EU AI Act & NIST RMF compliance',
      'Executive AI & board-level governance',
    ],
  },
  {
    id: 'software-engineering',
    icon: 'SE',
    title: 'Enterprise Software Engineering',
    description:
      'Production-grade backend systems, REST and GraphQL APIs, microservices, and SaaS platforms in C# .NET, Python FastAPI, and Node.js, built for enterprise scale.',
    tags: ['C# .NET', 'FastAPI', 'MERN', 'Microservices', 'GraphQL'],
    color: '#10275F',
    highlight: false,
    capabilities: [
      'C# ASP.NET Core 10 systems',
      'Python FastAPI services',
      'MERN stack SaaS platforms',
      'Microservices architecture',
      'RESTful & GraphQL APIs',
      'Event-driven systems (Azure Service Bus)',
    ],
  },
  {
    id: 'fintech-blockchain',
    icon: 'FX',
    title: 'FinTech & Blockchain',
    description:
      'Digital finance platforms, payment integrations, blockchain services, Web3 APIs, and regulatory-aware financial technology solutions for secure transaction flows.',
    tags: ['Solidity', 'Ethereum', 'Web3', 'DeFi', 'Payments'],
    color: '#6F5B22',
    highlight: false,
    capabilities: [
      'Ethereum smart contract development',
      'DeFi protocol integrations',
      'Digital payment gateway systems',
      'Web3.js / Ethers.js APIs',
      'Regulatory compliance (NUPRC/DPR)',
      'Financial data analytics',
    ],
  },
]

export default SERVICES
